### ISSUE TITLE
Support horizontal scrolling with FlexDirection.ROW

### ISSUE THREAD

**Issue by Saketme** [google/flexbox-layout#215]
Hello, thanks for this fantastic library. I'm trying to create a horizontally scrollable list, but `FlexboxLayoutManager` doesn't seem to be wrapping the list items. In each column, all items have the same width, which doesn't look correct. Is there something I'm missing? I'm using this code:

```
FlexboxLayoutManager flexboxLayoutManager = new FlexboxLayoutManager();
flexboxLayoutManager.setFlexWrap(FlexWrap.WRAP);
flexboxLayoutManager.setFlexDirection(FlexDirection.COLUMN);
```

**Update:** Oh wait, supplying `setAlignItems()` with something other than `STRETCH` fixes the width of the items. As in, they're no longer equi sized. So I've realized that I want the items to be laid out in row fashion, but the list should be horizontally scrollable. Is this possible?

**Comment by thagikura** [comment]
Hi @Saketme,

Currently horizontal scrolling is not supported if you set the flex direction as FlexDirection.ROW (or ROW_REVERSE).

But it could be implemented in the future, could you change the title as something like "Support horizontal scrolling with FlexDirection.ROW"?

**Comment by Saketme** [comment]
Done :)

**Comment by thagikura** [comment]
Thanks. I'll keep this as an enhancement.

**Comment by AnninaO** [comment]
Hi @thagikura !
I am looking for the same functionality, trying to make my FlexboxLayout wider than the actual screen and then make it scrollable. As this is not supported I tried to achieve it by wrapping it in a HorizontalScrollView, but unfortunately if I do that the wrapping doesn't work anymore. Is there any workaround how I can make the vertical scrolling possible for my FlexboxLayout?

**Comment by thagikura** [comment]
Hi @AnninaO,

At this moment, you can't scroll a RecyclerView with FlexboxLayoutManager in both directions.

**Comment by thagikura** [comment]
Fixed by #315

**Comment by MarioHBS** [comment]
Hello, the problem persists, when I put the FlexboxLayout (ROW mode) inside a HorizontalScrollView the items contract

**Comment by AbdoulMDiscovery** [comment]
> Hello, the problem persists, when I put the FlexboxLayout (ROW mode) inside a HorizontalScrollView the items contract

@MarioHBS were you able to resolve the issue? I am facing the same issue

**Comment by shahzadafridi** [comment]
This issue still exits.

**Comment by sheinin** [comment]
> > Hello, the problem persists, when I put the FlexboxLayout (ROW mode) inside a HorizontalScrollView the items contract
> 
> @MarioHBS were you able to resolve the issue? I am facing the same issue

Having the same issue

**Comment by bharat1320** [comment]
Guys I have found a solution, simply use ChipGroup instead of FlexBox , literally everything works fine as expected

**Comment by Okuro3499** [comment]
is there a fix for this issue? experienced this after upgrading my from
```implementation 'com.google.android:flexbox:1.0.0'```
to
```implementation 'com.google.android.flexbox:flexbox:3.0.0'```
and now items are now squeezed to fit screen which does not look good
![Screenshot 2023-09-29 14 46 53](https://github.com/google/flexbox-layout/assets/64019708/eb2bb7fa-d056-44c1-977b-0a7deb5d3e1a)
expected behavior is to display as shown in myteams and be scrollable horizontally

this is link to my xml https://github.com/open-learning-exchange/myplanet/blob/master/app/src/main/res/layout/home_card_library.xml

**Comment by shahaashit26** [comment]
Any solution to this ?
