### ISSUE TITLE
RecyclerView in RecyclerView with FlexboxLayoutManager only show one line

### ISSUE THREAD

**Issue by PPTing** [google/flexbox-layout#290]
I use a recyclerview(just call it the **ARecyclerView** with LinearLayoutManager ) and make another recyclerview(just call it the **BRecyclerView** with FlexboxLayoutManager) as the item of ARecyclerView**.

But after I call notifyDataSetChanged() ,the **BRecyclerView** only show one line whenever the data change. What I want is it should show more than one line because the BRecyclerView don't show all data.
The BRecyclerView layout is 
```xml
<android.support.v7.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/training_term_and_lesson_item_list"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    tools:listitem="@layout/training_item_venue_filter" />
```

and the item of BRecyclerView is
```xml
<?xml version="1.0" encoding="utf-8"?>
<CheckBox xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/training_item_venue_filter_venue_name"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginEnd="20dp"
    android:layout_marginRight="20dp"
    android:layout_marginTop="15dp"
    android:background="@drawable/commonsdk_bg_checkbox_corner_5"
    android:button="@null"
    android:gravity="center"
    android:minWidth="80dp"
    android:paddingBottom="7dp"
    android:paddingEnd="13dp"
    android:paddingLeft="13dp"
    android:paddingRight="13dp"
    android:paddingStart="13dp"
    android:paddingTop="7dp"
    android:textColor="@drawable/commonsdk_checkbox_text_color_normal_white"
    android:textSize="@dimen/commonsdk_super_small_text"
    tools:text="Hello World" />
```

## Expected behavior
What I want it show is 

## Version of the flexbox library
 0.3.0-alpha3*

**Comment by thagikura** [comment]
Hi @PPTing,

What parameters do you pass to the FlexboxLayoutManager? (e.g. FlexWrap, FlexDirection)
For example, if you pass FlexDirection.ROW and FlexWrap.NOWRAP, having a single line is expected.

**Comment by PPTing** [comment]
Hello @thagikura ,I new a FlexboxLayoutManager and not pass any parameters to the it, so the default value is `FlexDirection.ROW, FlexWrap.WRAP`
So how can I make the child RecyclerView( BRecyclerView) show all the view ? 
When I use GridLayoutManager, it can show all the view in child RecyclerView( BRecyclerView).
But when I use FlexboxLayoutManager , the child RecyclerView only show the height like only one line but I think it should show all the data and scroll it

**Comment by AlexTysel** [comment]
@thagikura I have the same issue as @PPTing . I pass` FlexDirection.ROW, FlexWrap.WRAP` to the `FlexboxLayoutManager`

**Comment by thagikura** [comment]
Sorry for the delayed comment. Confirmed the issue on my end.

Let me mark this as a bug.

**Comment by thagikura** [comment]
Should be fixed by #301

**Comment by Ratul-Bin-Tazul** [comment]
The issue is still present. 
Using 
layoutManager.setFlexDirection(FlexDirection.ROW);
layoutManager.setFlexWrap(FlexWrap.WRAP);

**Comment by IDevelopes** [comment]
Its 2020 and this issue is still present 😕

**Comment by akankshaldots** [comment]
The issue still exist.

**Comment by akankshapaul048** [comment]
The issue still exist. Time to check out other solution.

**Comment by cw-sanjeev** [comment]
@thagikura The issue still exists, is there any other fix
