### ISSUE TITLE
Horizontal scroll isn't handled correctly when layout direction is RTL and flex direction is row or row_reverse

### ISSUE THREAD

**Issue by thagikura** [google/flexbox-layout#318]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
- Set the layout direction as RTL
- Set the flex direction as row (or row_reverse)
- Set the width of the RecyclerView larger than its parent

## Expected behavior
RecyclerView can scroll horizontally without issues.

## Version of the flexbox library
0.3.0-alpha4

## Link to code
#317 is the code to fix this issue.

**Comment by thagikura** [comment]
Fixed by #317

**Comment by AlexanderChechyotko** [comment]
issue is still reproduced
https://codepen.io/AlexanderCh123/pen/OYwwRw
uncomment 'direction: rtl;'
