### ISSUE TITLE
Parent padding affects FlexboxLayout

### ISSUE THREAD

**Issue by PavelSynek** [google/flexbox-layout#36]
Setting padding to FlexboxLayout's parent adds left padding to FlexboxLayout itself. Did I misunderstand how some parameters work or is it a bug?
![device-2016-05-16-111316](https://cloud.githubusercontent.com/assets/11048800/15285480/9d8384b4-1b57-11e6-94c4-3eeca651547a.png)

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
	xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"
	android:layout_width="match_parent"
	android:layout_height="match_parent"
	android:padding="20dp">

	<com.google.android.flexbox.FlexboxLayout
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		app:alignContent="flex_start"
		app:alignItems="flex_start"
		app:flexDirection="row"
		app:flexWrap="wrap"
		app:justifyContent="flex_start">

		<TextView
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:padding="30dp"
			android:text="TEXTEXT"/>
		<TextView
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:padding="30dp"
			android:text="TEXTEXT"/>
		<TextView
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:padding="30dp"
			android:text="TEXTEXT"/>
		<TextView
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:padding="30dp"
			android:text="TEXTEXT"/>
		<TextView
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:padding="30dp"
			android:text="TEXTEXT"/>

	</com.google.android.flexbox.FlexboxLayout>

</FrameLayout>
```

**Comment by thagikura** [comment]
Looks like it's a bug for the FlexboxLayout. Thanks for reporting. I'll take a look.

**Comment by thagikura** [comment]
Should be fixed by #41 and I'll release the fixed version of the library anytime soon.

Thanks for the reporting again.

**Comment by novalu** [comment]
I'm using FlexboxLayout 0.2.0, but I think that text is still not wrapping correctly.

```

<com.google.android.flexbox.FlexboxLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="16dp"
    app:flexWrap="wrap">

    <TextView
        android:id="@+id/text1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="16sp"
        android:text="AAAAAAB"/>

    <TextView
        android:id="@+id/text2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="16sp"
        android:text="CCCCCCCCCCCCCCCCCCCCCCCC"/>

</com.google.android.flexbox.FlexboxLayout>
```

![flex](https://cloud.githubusercontent.com/assets/6546116/15760973/133386e8-2916-11e6-949f-aaf4729f4b41.png)

This layout is rendered as top image, then I added 'D' (middle image), then another 'D' (bottom image). In top and bottom render `FlexboxLayout` wrapped text correctly, but in middle render there are missing 'B' from `text1` and 'D' from `text2`. 

When changed attribute `layout_width` to `wrap_content`, behavior is different, but still incorrect.

![flexb](https://cloud.githubusercontent.com/assets/6546116/15761348/f8e7b50a-2917-11e6-96b7-54d17c12fdde.png)

In first image is the same text as above, then added 'E', another 'E' and once again 'E'.

**Comment by thagikura** [comment]
@novalu Thank you for your report!
Looks like that is a different issue. Could you file another issue for that?

**Comment by novalu** [comment]
Sorry, I was not certain whether it is duplicate or not. I've filed issue in #62 (and added some info).

**Comment by thagikura** [comment]
@novalu No worries. Thanks for filing!
