### ISSUE TITLE
FlexboxLayoutManager for AndroidX

### ISSUE THREAD

**Issue by herbeth1u** [google/flexbox-layout#433]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
Create an AndroidX-ready project targeting API 28 / Android P with a RecyclerView from the AndroidX package.
`implementation "androidx.recyclerview:recyclerview:1.0.0-alpha1"`
Try to assign a `FlexboxLayoutManager` to the RecyclerView : it doesn't compile because `FlexboxLayoutManager` extends `android.support.v7.widget.RecyclerView.LayoutManager` and not `androidx.recyclerview.widget.RecyclerView.LayoutManager`.
Note: `android.enableJetifier=true` doesn't seem to solve the problem.

## Expected behavior
There should be an AndroidX package for FlexboxLayout compatible with the AndroidX RecyclerView, like there is for LinearLayoutManager or GridLayoutManager (e.g. `android.support.v7.widget.LinearLayoutManager` refactored to `androidx.recyclerview.widget.LinearLayoutManager`).

## Version of the flexbox library
1.0.0

## Link to code
```kotlin
val recyclerView : androidx.recyclerview.widget.RecyclerView = ... // findViewById or whatever
recyclerView.layoutManager = FlexboxLayoutManager(this) // impossible
```

## Possible solution
Create a new androidx-packaged library and replace all `android.support` imports with `androidx` imports.

Thanks.

**Comment by thagikura** [comment]
Thanks for filing this.
I'll prioritize this.

**Comment by thagikura** [comment]
This is now fixed by #436

**Comment by adigyran** [comment]
Target sdk version 27, same error. Kotlin 1.2.71, support library 27.1.1, Android studio 3.2
Why?

**Comment by Anargyres** [comment]
Error still present : FlexboxLayoutManager extends android.support.v7.widget.RecyclerView.LayoutManager and not androidx.recyclerview.widget.RecyclerView.LayoutManager.
